In [2]:
import numpy as np

x = np.array([[0,-1,.25,0,0,0],[0,0,1,1,0, 4],[-2,0,0.5,2,1,2],[0,-3,2,0,2,6],[-1.3,0,0,1,0,0],[0,0,-11,0,0,48]])
x.shape

(6, 6)

In [2]:
y = np.array([[0],[6],[5],[10],[0],[0]])
y.shape

(6, 1)

In [8]:
c = np.matmul(np.linalg.inv(x),y)
c.shape

(6, 1)

In [9]:
c

array([[1.31953428],
       [0.55886158],
       [2.23544631],
       [1.71539457],
       [2.06597671],
       [0.51228978]])

In [18]:
x = np.array([[0,0,1,1,0,5],[-2, 0,.49,2,1,1],[0,-3,1.77,0,2,12],
              [0,-1,.24,0,0,0],[-1.4,0,0,1,0,0],[0,0,0,0,0,1]])
x.shape

(6, 6)

In [19]:
y = np.array([[6],[6],[12],[0],[0],[.153]])
y.shape


(6, 1)

In [20]:
c = np.matmul(np.linalg.inv(x),y)
c.shape

(6, 1)

In [21]:
c

array([[1.11687279],
       [0.88113074],
       [3.67137809],
       [1.56362191],
       [3.1545265 ],
       [0.153     ]])

In [4]:
x = np.array([[0,0,1,1,0,4],[-2, 0,.49,2,1,1],[0,-3,1.77,0,2,20],
              [0,-1,.24,0,0,0],[0,0,0,0,0,1],[0,0,1,0,0,0]])
x.shape

(6, 6)

In [5]:
y = np.array([[6],[6],[12],[0],[.041],[.026]])
y.shape

(6, 1)

In [6]:
c = np.matmul(np.linalg.inv(x),y)
c.shape

(6, 1)

In [7]:
c

array([[5.625045],
       [0.00624 ],
       [0.026   ],
       [5.81    ],
       [5.57635 ],
       [0.041   ]])